# Referências

CENIPA. (2022). NSCA 3-17. Sistema de Reportes do SIPAER para a Aviação Civil Brasileira.

CGNA. (2022) - Anuário Estatístico de Tráfego Aéreo / 2022. Rio de Janeiro.

DECEA. (2016). ICA 63-38 - Indicadores de Desempenho da Segurança Operacional do SISCEAB.

DECEA. (2021). ICA 63-33 Horário de Trabalho do Pessoal ATC, COM, MET, AIS, SAR e OPM.

DECEA. (2020). ICA 81-1 - Ocorrências de Tráfego Aéreo. 

DECEA. (2021). ICA 81-4 - Instrução que trata do Programa para Prevenção de Ocorrências de Incursão em Pista na Prestação dos Serviços de Tráfego Aéreo. 

DECEA. (2016). ICA 100-12 - Regras do Ar.

DECEA. (2017). ICA 100-19- Normas e Procedimentos para Operação do GCA. 

DECEA. (2018). ICA 100-22 - Serviço de Gerenciamento de Fluxo de Tráfego Aéreo.

DECEA. (2021). ICA 105-3 - Verificação Operacional.

DECEA. (2021). ICA 105-17 - Centros Meteorológicos. 

DECEA. (2022). ICA 800-8 -Garantia da Segurança AVSEC para o SISCEAB.

DECEA. (2014). MCA 100-17 - Capacidade de Setor ATC.

DECEA. (2020). MCA 100-22 - Metodologia de Indicadores ATM do SISCEAB.

DECEA. (2021). MCA 105-1 - Manual de Centro Meteorológico Militar.

DECEA. (2022). PCA 100-3 - Plano de Performance ATM do DECEA.

DECEA. (2020). PCA 11-353 - Plano Específico do Departamento de Controle do Espaço Aéreo para Mudança de Subordinação do DTCEA-IZ e do DTCEA-SL do CINDACTA IV e para o CINDACTA III.

ICAO. (2016). Doc 4444 - Procedures for Air Navigation Services (PANS) – Air Traffic Management (16th Edition).

ICAO. (2010). Doc 9.835 - Manual on the Imprementation of ICAO Language Proficiency Requirements (2nd Edition).

ICAO. Doc 9750. 6ª edição. Versão on-line: https://www4.icao.int/ganpportal/.

ICAO. (2019). Doc 9988 - “Guidance on the Development of States’ Action Plans on CO2 Emissions Reduction Activities”.

ICAO. (2017).  Doc 10118 - Global Aviation Security Plan.


